echo DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY >> .env
echo DJANGO_SUPER_USER_USERNAME=$DJANGO_SUPER_USER_USERNAME >> .env
echo DJANGO_SUPER_USER_PASSWORD=$DJANGO_SUPER_USER_PASSWORD >> .env
echo DJANGO_SUPERUSER_EMAIL=$DJANGO_SUPERUSER_EMAIL >> .env
