# Generated by Django 4.1.1 on 2022-09-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storageunit',
            old_name='currentStock',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='storageunit',
            name='orderpoint',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='storageunit',
            name='standardOrderAmount',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
