# Generated by Django 4.1.1 on 2022-09-29 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_storagecomponent_qrid'),
        ('backend', '0013_rename_price1_article_price'),
    ]

    operations = [
    ]
