# Generated by Django 4.1.1 on 2022-09-29 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_userinfo_user'),
        ('backend', '0015_article_storagecomponent'),
    ]

    operations = [
    ]
