# Generated by Django 4.1.1 on 2022-10-04 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('backend', '0017_remove_article_storagecomponent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='GroupInfo',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
