# Generated by Django 4.1.1 on 2022-10-03 16:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_groupinfo_rename_storagecomponent_storagespace_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('expectedWait', models.PositiveSmallIntegerField(default=0)),
                ('orderTime', models.DateTimeField(default=datetime.datetime.now)),
                ('ofArticle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.article')),
                ('toStorageUnit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.storageunit')),
            ],
        ),
        migrations.CreateModel(
            name='CentralStorageSpace',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.PositiveSmallIntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.article')),
            ],
        ),
    ]
