# Generated by Django 4.1.1 on 2022-10-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_order_centralstoragespace'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='order',
            name='hasArrived',
            field=models.BooleanField(default=False),
        ),
    ]
