<<<<<<< HEAD
# Generated by Django 4.1.1 on 2022-11-07 15:12
=======
# Generated by Django 4.1.1 on 2022-11-04 22:57
>>>>>>> 435c1b340103ed1471a32d529226a7de0e43aafb

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='time_of_transaction',
<<<<<<< HEAD
            field=models.DateField(blank=True, default=datetime.datetime(2022, 11, 7, 15, 12, 11, 947957, tzinfo=datetime.timezone.utc), null=True),
=======
            field=models.DateField(blank=True, default=datetime.datetime(2022, 11, 4, 22, 57, 31, 385062, tzinfo=datetime.timezone.utc), null=True),
>>>>>>> 435c1b340103ed1471a32d529226a7de0e43aafb
        ),
    ]
