# Generated by Django 4.1.1 on 2022-11-14 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': (('get_article', 'Can get articles from database'), ('post_article', 'Can create an article'), ('put_article', 'Can edit an article'), ('delete_article_new', 'Can delete an article'))},
        ),
        migrations.AlterModelOptions(
            name='compartment',
            options={'permissions': (('get_compartment', 'Can get compartments from database'), ('post_compartment', 'Can create a compartment'), ('put_compartment', 'Can edit a compartment'), ('delete_compartment_new', 'Can delete a compartment'))},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': (('get_order', 'Can get orders from database'), ('post_order', 'Can create an order'), ('put_order', 'Can edit an order'), ('delete_order_new', 'Can delete an order'))},
        ),
        migrations.AlterModelOptions(
            name='storage',
            options={'permissions': (('get_storage', 'Can get storages from database'), ('post_storage', 'Can create a storage'), ('put_storage', 'Can edit a storage'), ('delete_storage_new', 'Can delete a storage'))},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'permissions': (('get_transaction', 'Can get transactions from database'), ('post_transaction', 'Can create a transaction'), ('put_transaction', 'Can edit a transaction'), ('delete_transaction_new', 'Can delete a transaction'))},
        ),
    ]
