# Generated by Django 4.1.1 on 2022-11-17 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='barcodeId',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='nfcId',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
