# Generated by Django 4.1.1 on 2022-11-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='barcode_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
