# Generated by Django 4.1.1 on 2022-11-17 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.supplier'),
        ),
        migrations.AddField(
            model_name='article',
            name='supplierArticleNr',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
