# Generated by Django 4.1.1 on 2022-10-31 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlternativeArticles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('alternativearticle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.article')),
            ],
        ),
    ]
