# Generated by Django 4.1.1 on 2022-11-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderedarticle',
            name='output_per_input',
        ),
        migrations.AddField(
            model_name='orderedarticle',
            name='unit',
            field=models.CharField(default='input', max_length=10),
        ),
    ]
