# Generated by Django 4.1.1 on 2022-11-24 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'permissions': (('get_all_transaction', 'Can get all transactions'), ('get_transaction_by_id', 'Can get a transaction by id'), ('get_user_transactions', 'Can get a users transactions'), ('replenish', 'Can replenish articles to compartment'), ('move_article', 'Can move articles between compartments'))},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time_of_transaction',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
