# Generated by Django 4.1.1 on 2022-11-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='cost_center',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='cost_center',
            field=models.ManyToManyField(null=True, to='backend.costcenter'),
        ),
    ]
