# Generated by Django 4.1.1 on 2022-11-07 15:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='time_of_transaction',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 11, 7, 15, 12, 11, 947957, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
