# Generated by Django 4.1.1 on 2022-11-08 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': (('get_articles', 'Can get articles from database'),)},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time_of_transaction',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 11, 8, 10, 15, 39, 727742, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
