# Generated by Django 4.1.1 on 2022-11-04 16:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='time_of_transaction',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 11, 4, 16, 26, 35, 296146, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
