# Generated by Django 4.1.1 on 2022-09-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='alternative_names',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='refill_unit',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='sup_ordernr',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='supplier',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='take_out_unit',
            field=models.IntegerField(null=True),
        ),
    ]
