# Generated by Django 4.1.1 on 2022-11-30 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': (('post_article', 'Can create an article'), ('put_article', 'Can edit an article'), ('delete_article_new', 'Can delete an article'), ('view_article_perm', 'Can get article(s)'))},
        ),
        migrations.AlterModelOptions(
            name='compartment',
            options={'permissions': (('view_compartment_perm', 'Can view all compartments'),)},
        ),
        migrations.AlterModelOptions(
            name='groupinfo',
            options={'permissions': (('view_group_perm', 'Can view all groups'),)},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': (('get_order', 'Can get orders from database'), ('view_order_perm', 'Can get all orders'), ('add_order_perm', 'Can add orders'))},
        ),
        migrations.AlterModelOptions(
            name='storage',
            options={'permissions': (('get_storage_cost', 'Can see storage cost'), ('get_storage_value', 'Can see storage value'), ('return_to_storage', 'Can return article to storage'), ('add_input_unit', 'Can ad an input unit to storage'), ('view_storage_perm', 'Can see storage'))},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'permissions': (('get_all_transaction', 'Can get all transactions'), ('get_transaction_by_id', 'Can get a transaction by id'), ('get_user_transactions', 'Can get a users transactions'), ('replenish', 'Can replenish articles to compartment'), ('move_article', 'Can move articles between compartments'), ('add_transaction_perm', 'Can create transactions'), ('change_transaction_perm', 'Can create transactions'))},
        ),
    ]
