# Generated by Django 4.1.1 on 2022-11-17 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_article_supplier_article_supplierarticlenr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleHasSupplier',
        ),
    ]
