<<<<<<< HEAD
# Generated by Django 4.1.1 on 2022-11-09 16:27
=======
# Generated by Django 4.1.1 on 2022-11-08 09:10
>>>>>>> 435c1b340103ed1471a32d529226a7de0e43aafb

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_transaction_time_of_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='time_of_transaction',
<<<<<<< HEAD
            field=models.DateField(blank=True, default=datetime.datetime(2022, 11, 9, 16, 27, 25, 48119, tzinfo=datetime.timezone.utc), null=True),
=======
            field=models.DateField(blank=True, default=datetime.datetime(2022, 11, 8, 9, 10, 36, 778612, tzinfo=datetime.timezone.utc), null=True),
>>>>>>> 435c1b340103ed1471a32d529226a7de0e43aafb
        ),
    ]
