# Generated by Django 4.1.1 on 2022-11-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_userinfo_barcode_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_state',
            field=models.CharField(choices=[('order placed', 'Order Placed'), ('delivered', 'Delivered')], default='order placed', max_length=100),
        ),
    ]
