# Generated by Django 4.1.1 on 2022-12-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_article_options_alter_compartment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='output_per_input',
            field=models.IntegerField(default=1),
        ),
    ]
