# Generated by Django 4.1.1 on 2022-11-17 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_userinfo_barcodeid_userinfo_nfcid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='barcodeId',
            new_name='barcode_id',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='nfcId',
            new_name='nfc_id',
        ),
    ]
