# Generated by Django 4.1.1 on 2022-10-31 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alternativearticles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alternativearticles',
            old_name='alternativearticle',
            new_name='alternative_article',
        ),
    ]
