# Generated by Django 4.1.1 on 2022-11-09 16:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_transaction_time_of_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='time_of_transaction',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 11, 9, 16, 27, 25, 48119, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
