# Generated by Django 4.1.1 on 2022-09-29 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_rename_currentstock_storageunit_amount_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='storageUnit',
            new_name='storageComponent',
        ),
    ]
