# Generated by Django 4.1.1 on 2022-11-08 09:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_transaction_time_of_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='time_of_transaction',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 11, 8, 9, 10, 36, 778612, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
