# Generated by Django 4.1.1 on 2022-11-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_orderedarticle_output_per_input_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedarticle',
            name='unit',
            field=models.IntegerField(choices=[(1, 'Input'), (2, 'Output')], default=1),
        ),
    ]
