# Generated by Django 4.1.1 on 2022-11-09 13:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_transaction_time_of_transaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': [('get_article', 'Can get articles from database')]},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time_of_transaction',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 11, 9, 13, 6, 43, 745362, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
