# Generated by Django 4.1.1 on 2022-10-31 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_rename_alternativearticle_alternativearticles_alternative_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlternativeArticles',
        ),
    ]
