# Generated by Django 4.1.1 on 2022-11-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_orderedarticle_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='input',
            field=models.IntegerField(choices=[(1, 'Millilitres'), (2, 'Centilitres'), (3, 'Decilitres'), (4, 'Litres'), (5, 'Millimetres'), (6, 'Centimetres'), (7, 'Metres'), (8, 'Pieces'), (9, 'Crates'), (10, 'Bottles')], default=1),
        ),
        migrations.AddField(
            model_name='article',
            name='output',
            field=models.IntegerField(choices=[(1, 'Millilitres'), (2, 'Centilitres'), (3, 'Decilitres'), (4, 'Litres'), (5, 'Millimetres'), (6, 'Centimetres'), (7, 'Metres'), (8, 'Pieces'), (9, 'Crates'), (10, 'Bottles')], default=1),
        ),
        migrations.AddField(
            model_name='article',
            name='output_per_input',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
