# Generated by Django 4.1.1 on 2022-11-10 15:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_transaction_time_of_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_time',
            new_name='order_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='expected_wait',
        ),
        migrations.RemoveField(
            model_name='order',
            name='of_article',
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_delivery_date',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_state',
            field=models.IntegerField(choices=[(1, 'Order Placed'), (2, 'Handled At The Central Depot'), (3, 'In Transit'), (4, 'Delivered'), (5, 'In Storage')], default=1),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='operation',
            field=models.IntegerField(choices=[(1, 'Takeout'), (2, 'Return'), (3, 'Replenish'), (4, 'Adjust')], default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time_of_transaction',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.DeleteModel(
            name='QRCode',
        ),
    ]
