# Generated by Django 4.1.1 on 2022-11-17 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_delete_articlehassupplier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='supplierArticleNr',
            new_name='supplier_article_nr',
        ),
    ]
