# Generated by Django 4.1.1 on 2022-11-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_rename_barcodeid_userinfo_barcode_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='cost_center',
            field=models.ManyToManyField(null=True, to='backend.costcenter'),
        ),
    ]
