# Generated by Django 4.1.1 on 2022-11-10 16:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_transaction_time_of_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='operation',
            field=models.IntegerField(choices=[(1, 'Takeout'), (2, 'Return'), (3, 'Replenish'), (4, 'Adjust')], default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time_of_transaction',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
