# Generated by Django 4.1.1 on 2022-09-29 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_rename_storageunit_storagecomponent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagecomponent',
            name='qrId',
            field=models.CharField(default='0', max_length=15, primary_key=True, serialize=False),
        ),
    ]
