# Generated by Django 4.1.1 on 2022-11-09 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_article_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': (('get_article', 'Can get articles from database'),)},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time_of_transaction',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 11, 9, 13, 9, 24, 578741, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
