# Generated by Django 4.1.1 on 2022-11-14 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_transaction_operation'),
        ('backend', '0004_alter_transaction_operation_and_more'),
    ]

    operations = [
    ]
