# Generated by Django 4.1.1 on 2022-11-22 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_order_delivery_date'),
        ('backend', '0004_rename_supplierarticlenr_article_supplier_article_nr'),
    ]

    operations = [
    ]
