# Generated by Django 4.1.1 on 2022-11-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_article_input_article_output_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedarticle',
            name='unit',
            field=models.CharField(choices=[('input', 'Input'), ('output', 'Output')], default='input', max_length=10),
        ),
    ]
