# Generated by Django 4.1.1 on 2022-11-21 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_userinfo_cost_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='cost_center',
            field=models.ManyToManyField(to='backend.costcenter'),
        ),
    ]
