# Generated by Django 4.1.1 on 2022-11-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_orderedarticle_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='input',
            field=models.IntegerField(choices=[(1, 'ml'), (2, 'cl'), (3, 'dl'), (4, 'l'), (5, 'mm'), (6, 'cm'), (7, 'm'), (8, 'pieces'), (9, 'crates'), (10, 'Bottles')], default=1),
        ),
        migrations.AlterField(
            model_name='article',
            name='output',
            field=models.IntegerField(choices=[(1, 'ml'), (2, 'cl'), (3, 'dl'), (4, 'l'), (5, 'mm'), (6, 'cm'), (7, 'm'), (8, 'pieces'), (9, 'crates'), (10, 'Bottles')], default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_state',
            field=models.IntegerField(choices=[(1, 'order placed'), (2, 'handled at central depo'), (3, 'order in transit'), (4, 'order delivered'), (5, 'order in storage')], default=1),
        ),
    ]
