# Generated by Django 4.1.1 on 2022-11-01 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputoutput',
            name='inputUnitName',
            field=models.CharField(default='input', max_length=30),
        ),
        migrations.AlterField(
            model_name='inputoutput',
            name='outputUnitName',
            field=models.CharField(default='output', max_length=30),
        ),
        migrations.AlterField(
            model_name='inputoutput',
            name='outputUnitPerInputUnit',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
