# Generated by Django 4.1.1 on 2022-11-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_article_input_alter_article_output_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_state',
            field=models.CharField(choices=[('1', 'order placed'), ('2', 'handled at central depo'), ('3', 'order in transit'), ('4', 'order delivered'), ('5', 'order in storage')], default='1', max_length=20),
        ),
    ]
