# Generated by Django 4.1.1 on 2022-09-28 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_group',
            field=models.ManyToManyField(to='backend.group'),
        ),
    ]
