# Generated by Django 4.1.1 on 2022-11-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_order_order_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='input',
            field=models.CharField(choices=[('ml', 'Millilitres'), ('cl', 'Centilitres'), ('dl', 'Decilitres'), ('l', 'Litres'), ('mm', 'Millimetres'), ('cm', 'Centimetres'), ('m', 'Metres'), ('pieces', 'Pieces'), ('crates', 'Crates'), ('bottles', 'Bottles')], default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='output',
            field=models.CharField(choices=[('ml', 'Millilitres'), ('cl', 'Centilitres'), ('dl', 'Decilitres'), ('l', 'Litres'), ('mm', 'Millimetres'), ('cm', 'Centimetres'), ('m', 'Metres'), ('pieces', 'Pieces'), ('crates', 'Crates'), ('bottles', 'Bottles')], default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_state',
            field=models.CharField(choices=[(1, 'Order Placed'), (2, 'Handled At The Central Depot'), (3, 'In Transit'), (4, 'Delivered'), (5, 'In Storage')], default=1, max_length=20),
        ),
    ]
