# Generated by Django 4.1.1 on 2022-11-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_supplier_alter_article_sanitation_level_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='sanitation_level',
            new_name='Z41',
        ),
        migrations.AddField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
