# Generated by Django 4.1.1 on 2022-09-28 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_article_article_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='minimal_order_qt',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='std_cost',
            field=models.IntegerField(null=True),
        ),
    ]
