# Generated by Django 4.1.1 on 2022-11-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_rename_sanitation_level_article_z41_supplier_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlehassupplier',
            name='supplier_article_nr',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
