# Generated by Django 4.1.1 on 2022-11-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_article_input_alter_article_output_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_state',
            field=models.CharField(choices=[('order placed', 'Order Placed'), ('handled at central depo', 'Handled At The Central Depot'), ('in transit', 'In Transit'), ('delivered', 'Delivered'), ('in storage', 'In Storage')], default='order placed', max_length=100),
        ),
    ]
