# Generated by Django 4.1.1 on 2022-09-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_article_minimal_order_qt_article_std_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='alternative_articles',
            field=models.ManyToManyField(blank=True, to='backend.article'),
        ),
    ]
