# Generated by Django 4.1.1 on 2022-11-01 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alternativearticlename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='alternative_names',
        ),
    ]
