# Generated by Django 4.1.1 on 2022-11-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_article_input_alter_article_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_state',
            field=models.CharField(choices=[('order placed', 'Order Placed'), ('partially delivered', 'Partially Delivered'), ('delivered', 'Delivered')], default='order placed', max_length=100),
        ),
    ]
