# Generated by Django 4.1.1 on 2022-11-01 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_storagespace_article'),
        ('backend', '0011_remove_article_alternative_names'),
    ]

    operations = [
    ]
