# Generated by Django 4.1.1 on 2022-09-29 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_remove_group_articles_remove_article_article_group_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='price',
            new_name='price1',
        ),
    ]
