# Generated by Django 4.1.1 on 2022-11-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_merge_20221101_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='refill_unit',
            field=models.IntegerField(choices=[(1, 'Millilitres'), (2, 'Centilitres'), (3, 'Decilitres'), (4, 'Litres'), (5, 'Millimetres'), (6, 'Centimetres'), (7, 'Metres'), (8, 'Pieces'), (9, 'Crates'), (10, 'Bottles')], default=1),
        ),
        migrations.AddField(
            model_name='article',
            name='takeout_unit',
            field=models.IntegerField(choices=[(1, 'Millilitres'), (2, 'Centilitres'), (3, 'Decilitres'), (4, 'Litres'), (5, 'Millimetres'), (6, 'Centimetres'), (7, 'Metres'), (8, 'Pieces'), (9, 'Crates'), (10, 'Bottles')], default=1),
        ),
    ]
