# Generated by Django 4.1.1 on 2022-09-29 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_rename_price_article_price1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='price1',
            new_name='price',
        ),
    ]
