# Generated by Django 4.1.1 on 2022-11-03 10:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_alter_inputoutput_inputunitname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='time_of_transaction',
        ),
        migrations.AddField(
            model_name='transaction',
            name='time_stamp',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
