# Generated by Django 4.1.1 on 2022-11-03 14:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_remove_transaction_time_of_transaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='time_stamp',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
