# Generated by Django 4.1.1 on 2022-09-29 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_merge_20220929_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='storageComponent',
        ),
    ]
