# Generated by Django 4.1.1 on 2022-11-04 14:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_alter_transaction_time_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='time_stamp',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 11, 4, 14, 51, 38, 883257, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
