# Generated by Django 4.1.1 on 2022-10-11 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_qrcode_order_centralstoragespace'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='alternative_articles',
            field=models.ManyToManyField(blank=True, to='backend.article'),
        ),
        migrations.AddField(
            model_name='article',
            name='alternative_names',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='sanitation_level',
            field=models.CharField(default=0, max_length=30, null=True),
        ),
    ]
