<<<<<<< HEAD
# Generated by Django 4.1.1 on 2022-10-11 08:00

from django.db import migrations, models
=======
# Generated by Django 4.1.1 on 2022-10-12 06:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
>>>>>>> 98ebf358e79bc37666fc698b6c0be976ebcba098


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
=======
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> 98ebf358e79bc37666fc698b6c0be976ebcba098
        ('backend', '0021_qrcode_order_centralstoragespace'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='alternative_articles',
            field=models.ManyToManyField(blank=True, to='backend.article'),
        ),
        migrations.AddField(
            model_name='article',
            name='alternative_names',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='sanitation_level',
            field=models.CharField(default=0, max_length=30, null=True),
        ),
<<<<<<< HEAD
=======
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.PositiveIntegerField(default=None)),
                ('timeOfTransaction', models.DateTimeField(default=datetime.datetime.now)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.article')),
                ('byUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('toStorageUnit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.storageunit')),
            ],
        ),
        migrations.CreateModel(
            name='InputOutput',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('inputUnitName', models.CharField(max_length=30)),
                ('outputUnitName', models.CharField(max_length=30)),
                ('outputUnitPerInputUnit', models.PositiveIntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.article')),
            ],
        ),
>>>>>>> 98ebf358e79bc37666fc698b6c0be976ebcba098
    ]
