# Generated by Django 4.1.1 on 2022-10-12 09:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_article_alternative_articles_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='byUser',
            new_name='by_user',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='toStorageUnit',
            new_name='storage_unit',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='timeOfTransaction',
        ),
        migrations.AddField(
            model_name='transaction',
            name='operation',
            field=models.IntegerField(choices=[(1, 'Takeout'), (2, 'Return'), (3, 'Replenish'), (4, 'Adjust')], default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='time_of_transaction',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
