# Generated by Django 4.1.1 on 2022-10-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_rename_byuser_transaction_by_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='time_of_transaction',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
